/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary': 'var(--color-primary)',
        'secondary': 'var(--color-secondary)',
        'tertiary': 'var(--color-tertiary)',
        'light-bg': 'var(--color-light-background)',
        'dark-bg': 'var(--color-dark-background)',
        'primary-accent': 'var(--color-primary-accent)',
        'secondary-accent': 'var(--color-secondary-accent)',
        'tertiary-accent': 'var(--color-tertiary-accent)',
        'error': 'var(--color-error)',
        'completed': 'var(--color-completed)',
        'good': 'var(--color-good)',
        // Phase 14 two-layer palette (handoff design tokens)
        'backdrop': 'var(--backdrop)',
        'brand': 'var(--brand)',
        'canvas': 'var(--canvas)',
        'canvas2': 'var(--canvas2)',
        'card': 'var(--card)',
        'card2': 'var(--card2)',
        'zebra': 'var(--zebra)',
        'forest': 'var(--forest)',
        'ink': 'var(--ink)',
        'cream': 'var(--cream)',
        'teal': 'var(--teal)',
        'tealink': 'var(--tealink)',
        'tealink-hover': 'var(--tealink-hover)',
        'ggbubble': 'var(--ggbubble)',
        'peach': 'var(--peach)',
        'amber': 'var(--amber)',
        'terracotta': 'var(--terracotta)',
        'eyebrow': 'var(--eyebrow)',
        'disclosure': 'var(--disclosure)',
        'disclosure-ink': 'var(--disclosure-ink)',
      },
      fontFamily: {
        'playfair': ['var(--font-playfair)', 'Georgia', 'serif'],
        'bebas': ['var(--font-bebas)', 'Impact', 'sans-serif'],
        'hanken': ['var(--font-hanken)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}